/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgSchema,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const db_schema = pgSchema('payload')
export const enum_users_role = db_schema.enum('enum_users_role', [
  'admin',
  'user',
])
export const enum_posts_category = db_schema.enum('enum_posts_category', [
  'Product',
  'Engineering',
  'Guides',
  'Updates',
])
export const enum_posts_status = db_schema.enum('enum_posts_status', [
  'published',
  'draft',
])

export const users_sessions = db_schema.table(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const users = db_schema.table(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    role: enum_users_role('role').notNull().default('admin'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ]
)

export const links = db_schema.table(
  'links',
  {
    id: serial('id').primaryKey(),
    domain: varchar('domain').notNull(),
    url: varchar('url').notNull(),
    description: varchar('description'),
    clicks: numeric('clicks', { mode: 'number' }).default(0),
    creatorEmail: varchar('creator_email'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('links_domain_idx').on(columns.domain),
    index('links_updated_at_idx').on(columns.updatedAt),
    index('links_created_at_idx').on(columns.createdAt),
  ]
)

export const pages = db_schema.table(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    hero_badgeText: varchar('hero_badge_text').default(
      'Find the project on Github'
    ),
    hero_badgeUrl: varchar('hero_badge_url').default(
      'https://github.com/rajuapp/link'
    ),
    hero_heading: varchar('hero_heading').default(
      'Create Links Simply, All in One Place'
    ),
    hero_subheading: varchar('hero_subheading').default(
      'Effortlessly generate shortened links and efficiently manage them all in one centralized dashboard.'
    ),
    hero_primaryButtonText: varchar('hero_primary_button_text').default(
      'Get Started'
    ),
    hero_primaryButtonUrl: varchar('hero_primary_button_url').default('/login'),
    hero_secondaryButtonText: varchar('hero_secondary_button_text').default(
      'Github'
    ),
    hero_secondaryButtonUrl: varchar('hero_secondary_button_url').default(
      'https://github.com/rajuapp/link'
    ),
    hero_media: integer('hero_media_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    hero_imageUrl: varchar('hero_image_url').default('/mockup.jpg'),
    hero_imageAlt: varchar('hero_image_alt').default('Link Dashboard Preview'),
    content: jsonb('content'),
    metricsSection_showMetrics: boolean('metrics_section_show_metrics').default(
      true
    ),
    metricsSection_heading: varchar('metrics_section_heading').default(
      'Active Metrics'
    ),
    metricsSection_subheading: varchar('metrics_section_subheading').default(
      'Real-time performance and link analytics'
    ),
    featuresSection_showFeatures: boolean(
      'features_section_show_features'
    ).default(true),
    featuresSection_badgeText: varchar('features_section_badge_text').default(
      'Features'
    ),
    featuresSection_heading: varchar('features_section_heading').default(
      'Powerful Features for Streamlined Link Management'
    ),
    featuresSection_subheading: varchar('features_section_subheading').default(
      'This app presents a variety of features tailored to simplify and enhance your link management experience. From customizable short URLs to detailed analytics and link history.'
    ),
    featuresSection_media: integer('features_section_media_id').references(
      () => media.id,
      {
        onDelete: 'set null',
      }
    ),
    featuresSection_imageUrl: varchar('features_section_image_url').default(
      '/mockup2.png'
    ),
    featuresSection_imageAlt: varchar('features_section_image_alt').default(
      'Link Features Overview'
    ),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_hero_hero_media_idx').on(columns.hero_media),
    index('pages_features_section_features_section_media_idx').on(
      columns.featuresSection_media
    ),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ]
)

export const posts = db_schema.table(
  'posts',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    excerpt: varchar('excerpt').notNull(),
    content: jsonb('content').notNull(),
    category: enum_posts_category('category').notNull().default('Product'),
    author: varchar('author').default('Link Team'),
    authorRole: varchar('author_role').default('Product & Engineering'),
    readingTime: varchar('reading_time').default('3 min read'),
    tags: varchar('tags').default('Product, URL Shortener'),
    status: enum_posts_status('status').notNull().default('published'),
    publishedAt: timestamp('published_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('posts_slug_idx').on(columns.slug),
    index('posts_updated_at_idx').on(columns.updatedAt),
    index('posts_created_at_idx').on(columns.createdAt),
  ]
)

export const media = db_schema.table(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ]
)

export const payload_kv = db_schema.table(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)]
)

export const payload_locked_documents = db_schema.table(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ]
)

export const payload_locked_documents_rels = db_schema.table(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    linksID: integer('links_id'),
    pagesID: integer('pages_id'),
    postsID: integer('posts_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_links_id_idx').on(columns.linksID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_posts_id_idx').on(columns.postsID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['linksID']],
      foreignColumns: [links.id],
      name: 'payload_locked_documents_rels_links_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['postsID']],
      foreignColumns: [posts.id],
      name: 'payload_locked_documents_rels_posts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
  ]
)

export const payload_preferences = db_schema.table(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ]
)

export const payload_preferences_rels = db_schema.table(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ]
)

export const payload_migrations = db_schema.table(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ]
)

export const settings_footer_links = db_schema.table(
  'settings_footer_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    url: varchar('url').notNull(),
    newTab: boolean('new_tab').default(false),
  },
  (columns) => [
    index('settings_footer_links_order_idx').on(columns._order),
    index('settings_footer_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [settings.id],
      name: 'settings_footer_links_parent_id_fk',
    }).onDelete('cascade'),
  ]
)

export const settings = db_schema.table('settings', {
  id: serial('id').primaryKey(),
  footer_tagline: varchar('footer_tagline').default(
    'Your link shortening companion, built for speed and simplicity.'
  ),
  footer_authorName: varchar('footer_author_name').default('raju.app'),
  footer_authorUrl: varchar('footer_author_url').default(
    'https://github.com/rajuapp'
  ),
  footer_githubUrl: varchar('footer_github_url').default(
    'https://github.com/rajuapp/link'
  ),
  footer_copyright: varchar('footer_copyright').default(
    '© 2026 Link. All rights reserved.'
  ),
  updatedAt: timestamp('updated_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp('created_at', {
    mode: 'string',
    withTimezone: true,
    precision: 3,
  }),
})

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: 'sessions',
    }),
  })
)
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_links = relations(links, () => ({}))
export const relations_pages = relations(pages, ({ one }) => ({
  hero_media: one(media, {
    fields: [pages.hero_media],
    references: [media.id],
    relationName: 'hero_media',
  }),
  featuresSection_media: one(media, {
    fields: [pages.featuresSection_media],
    references: [media.id],
    relationName: 'featuresSection_media',
  }),
}))
export const relations_posts = relations(posts, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    linksID: one(links, {
      fields: [payload_locked_documents_rels.linksID],
      references: [links.id],
      relationName: 'links',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    postsID: one(posts, {
      fields: [payload_locked_documents_rels.postsID],
      references: [posts.id],
      relationName: 'posts',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
  })
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  })
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  })
)
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: '_rels',
    }),
  })
)
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({})
)
export const relations_settings_footer_links = relations(
  settings_footer_links,
  ({ one }) => ({
    _parentID: one(settings, {
      fields: [settings_footer_links._parentID],
      references: [settings.id],
      relationName: 'footer_links',
    }),
  })
)
export const relations_settings = relations(settings, ({ many }) => ({
  footer_links: many(settings_footer_links, {
    relationName: 'footer_links',
  }),
}))

type DatabaseSchema = {
  db_schema: typeof db_schema
  enum_users_role: typeof enum_users_role
  enum_posts_category: typeof enum_posts_category
  enum_posts_status: typeof enum_posts_status
  users_sessions: typeof users_sessions
  users: typeof users
  links: typeof links
  pages: typeof pages
  posts: typeof posts
  media: typeof media
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  settings_footer_links: typeof settings_footer_links
  settings: typeof settings
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_links: typeof relations_links
  relations_pages: typeof relations_pages
  relations_posts: typeof relations_posts
  relations_media: typeof relations_media
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_settings_footer_links: typeof relations_settings_footer_links
  relations_settings: typeof relations_settings
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
